package Modules;
import Engine.Game;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;

public class Board extends javax.swing.JFrame {

    static JLabel[][] beads;

    public Board() {
        initComponents();
        setLocationRelativeTo(null);
        playersButton.add(player1Button);
        playersButton.add(player2Button);

        beads = new JLabel[3][3];
        for (int row = 0; row < 3; row++) {
            for (int col = 0; col < 3; col++) {
                beads[row][col] = new JLabel();
                beads[row][col].setVisible(true);
                beads[row][col].setSize(70, 70);
                beads[row][col].setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/N_PLACED.png")));
                beads[row][col].setLocation(70 * col, 70 * row);
                add(beads[row][col]);
                boardPanel.add(beads[row][col]);
                int r = row;
                int c = col;
                JLabel bead = beads[row][col];
                bead.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        Game.getCurrentState().placeBead(Game.getTurn().getPlayerBead(), r, c);
                        showCurrentState();
                        Game.switchTurn();
                        Game.playComputerTurn();
                        bead.removeMouseListener(this);
                    }
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playersButton = new javax.swing.ButtonGroup();
        boardPanel = new javax.swing.JPanel();
        statusPanel = new javax.swing.JPanel();
        turnLabel = new javax.swing.JLabel();
        choosePlayerPanel = new javax.swing.JPanel();
        player1Button = new javax.swing.JRadioButton();
        player2Button = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 500));
        setPreferredSize(new java.awt.Dimension(400, 500));
        getContentPane().setLayout(null);

        boardPanel.setMinimumSize(new java.awt.Dimension(210, 210));
        boardPanel.setName(""); // NOI18N
        boardPanel.setLayout(null);
        getContentPane().add(boardPanel);
        boardPanel.setBounds(90, 30, 210, 260);

        statusPanel.setLayout(null);

        turnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/X_TURN.png"))); // NOI18N
        statusPanel.add(turnLabel);
        turnLabel.setBounds(20, 0, 70, 70);

        getContentPane().add(statusPanel);
        statusPanel.setBounds(80, 380, 230, 70);

        choosePlayerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        choosePlayerPanel.setLayout(null);

        player1Button.setText("Player 1");
        choosePlayerPanel.add(player1Button);
        player1Button.setBounds(40, 10, 140, 23);

        player2Button.setText("Player 2");
        choosePlayerPanel.add(player2Button);
        player2Button.setBounds(40, 40, 120, 23);

        getContentPane().add(choosePlayerPanel);
        choosePlayerPanel.setBounds(60, 280, 270, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showCurrentState() {
        for (int row = 0; row < 3; row++) {
            for (int col = 0; col < 3; col++) {
                beads[row][col].setIcon(new javax.swing.ImageIcon("src\\images\\" + Game.getCurrentState().getCells()[row][col] + "_PLACED.png"));
            }
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Board().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boardPanel;
    private javax.swing.JPanel choosePlayerPanel;
    private javax.swing.JRadioButton player1Button;
    private javax.swing.JRadioButton player2Button;
    private javax.swing.ButtonGroup playersButton;
    private javax.swing.JPanel statusPanel;
    public javax.swing.JLabel turnLabel;
    // End of variables declaration//GEN-END:variables
}
